### ISSUE TITLE
Add to Non-Player Character list

### ISSUE THREAD

**Issue by roberthd008** [r2luna/cs160#7]
**As a:** player
**I want to be able to:**
Create a list of non-player characters with descriptions of each including 

- [ ] race 
- [ ] class
- [ ] inventory (list of items)
- [ ] hit points (number)
- [ ] List of attacks 
            attack number
            attack type
- [ ] armor class (number)

**so that I can:**
easily keep track of and pull up non-player characters when necessary.

**Comment by roberthd008** [comment]
As a: player
**I want to be able to:**
Create a list of non-player characters with descriptions of each including race, class, inventory, and few essential stats such hit points, attacks, and armor class.
**so that I can:**
easily keep track of and pull up non-player characters when necessary.

**Comment by roberthd008** [comment]
Great job guys!
-RHD
